### PR TITLE
Add SDK as submodule and add initial files

### PR DESCRIPTION
**Pull request by kchitalia**

### CODE REVIEW

**Comment by bhariharan** [comment]
This should probably go against the `unstable` branch here.

**Comment by smcnulty-sfdc** [comment]
Also, add a gitignore and make sure you don't check in all the nuget files.

**Comment by kchitalia** [comment]
@bhariharan This is pointing to the latest commit on unstable branch of SDK.

**Comment by bhariharan** [comment]
Yes, I meant the branch in this repo should probably also be `unstable`. Right now it's going against `master`.

**Comment by kchitalia** [comment]
Thats right. Thanks for pointing it out. I'll close this one and make a new PR against unstable

**Pull request closed without merging**
